---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
#  - name: centos-7.3

suites:
  - name: default
    driver:
      vm_hostname: testmachine.com
      network:
      - ["private_network", {ip: "192.168.10.99"}]
    run_list:
      - recipe[dokuwiki::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
